version: '3.5'

services:

  nginx:
    image: glrd/nginx
    build:
      context: ./
      dockerfile: nginx.dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./nginx/config:/etc/nginx/conf.d/
      - ./nginx/logs:/var/logs
    links:
      - php:php
    networks:
      - devnet

  php:
    image: glrd/laravel
    build:
      context: ./
      dockerfile: php.dockerfile
#    volumes:
#      - ./src/lara-test:/var/www/html
    container_name: nginx-php
    command: php-fpm --allow-to-run-as-root
    privileged: true
    links:
      - mysql
    networks:
      - mysqlnet
      - devnet

  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
 #   volumes:
 #     - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=init_db
    networks:
      - mysqlnet

networks:
  devnet:
    name: devnet
    driver: bridge
  mysqlnet:
    name: mysqlnet
    driver: bridge
